# Generated by Django 2.1.2 on 2018-10-26 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='pid',
            field=models.ForeignKey(db_column='pid', on_delete=django.db.models.deletion.CASCADE, to='auth.permissions.Permission'),
        ),
        migrations.AlterModelTable(
            name='permission',
            table='permission',
        ),
    ]
